export enum TextColor {
  Default = `39m`,
  Black = `30m`,
  Red = `31m`,
  Green = `32m`,
  Yellow = `33m`,
  Blue = `34m`,
  Magenta = `35m`,
  Cyan = `36m`,
  LightGray = `37m`,
  DarkGray = `90m`,
  LightRed = `91m`,
  LightGreen = `92m`,
  LightYellow = `93m`,
  LightBlue = `94m`,
  LightMagenta = `95m`,
  LightCyan = `96m`,
  White = `97m`,
}

export enum BackgroundColor {
  Default = `49m`,
  Black = `40m`,
  Red = `41m`,
  Green = `42m`,
  Yellow = `43m`,
  Blue = `44m`,
  Magenta = `45m`,
  Cyan = `46m`,
  LightGray = `47m`,
  DarkGray = `100m`,
  LightRed = `101m`,
  LightGreen = `102m`,
  LightYellow = `103m`,
  LightBlue = `104m`,
  LightMagenta = `105m`,
  LightCyan = `106m`,
  White = `107m`,
}

export enum TextStyle {
  Reset = `0m`,
  Bold = `1m`,
  Dim = `2m`,
  Italic = `3m`,
  Underline = `4m`,
  Blink = `5m`,
  Reverse = `7m`,
  Hidden = `8m`,
  Strikethrough = `9m`,
}
