name: Code Checks
on:
  workflow_dispatch: # for testing purposes, this should be deleted
  pull_request:
    branches:
      - main
jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-node-modules-
      - name: Install Root Dependencies
        run: npm install
      - name: Install Package Dependencies
        run: npm install --workspaces
      - name: Build Packages
        run: npm run build
      - name: Formatting
        run: npm run format
      - name: Linting
        run: npm run lint
      - name: Type Checking
        run: npm run type-check
      - name: Test Coverage
        run: npm run coverage
