name: Code Checks
on:
  workflow_dispatch: # for testing purposes, this should be deleted
  pull_request:
    branches:
      - main
jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm un install
      - name: Build Packages
        run: npm run build
      - name: Formatting
        run: npm run format
      - name: Linting
        run: npm run lint
      - name: Type Checking
        run: npm run type-check --workspaces
      - name: Test Coverage
        run: npm run coverage --workspaces
