name: Code Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Setup & Installation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-node-modules-
      - name: Install Root Dependencies
        run: npm install
      - name: Install Package Dependencies
        run: npm install --workspaces
      - name: Build Packages
        run: npm run build
      - name: Zip node_modules
        run: tar -czf node_modules.tar.gz node_modules/
      - name: Upload node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules.tar.gz
  formatting:
    name: Code Formatting
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: .
      - name: Unzip node_modules
        run: tar -xzf node_modules.tar.gz
      - name: Formatting
        run: npm run format
  linting:
    name: Linting
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: .
      - name: Unzip node_modules
        run: tar -xzf node_modules.tar.gz
      - name: Linting
        run: npm run lint
  type-check:
    name: Type Checking
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: .
      - name: Unzip node_modules
        run: tar -xzf node_modules.tar.gz
      - name: Type Checking
        run: npm run type-check
  coverage:
    name: Test Coverage
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: .
      - name: Unzip node_modules
        run: tar -xzf node_modules.tar.gz
      - name: Test Coverage
        run: npm run coverage
