name: Publish Packages
on:
  release:
    types: [published]
jobs:
  # TODO: bump-version:
  # Based on "v0.0.0" tag
  # extract version "0.0.0"
  # apply it to all sub-packages
  # commit to release branch
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   ref: release
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --workspaces
      - run: npm run build --workspaces
      - run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
