name: Publish packages to npm
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --workspaces

      - name: Build @rebel-framework/core
        run: cd packages/core && npm run build

      - name: Build @rebel-framework/stack
        run: cd packages/stack && npm run build

      - name: Build @rebel-framework/cli
        run: cd packages/cli && npm run build

      - name: Publish
      - run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
